# Generated by Django 5.2 on 2025-04-05 06:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "registration_app",
            "0003_alter_propertyinfo_category_alter_propertyinfo_city_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyinfo",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
    ]
