# Generated by Django 5.2 on 2025-04-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration_app", "0004_propertyinfo_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyinfo",
            name="password",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
