# Generated by Django 5.2 on 2025-04-23 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration_app", "0007_alter_propertyinfo_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("one_sharing_price", models.PositiveIntegerField()),
                ("two_sharing_price", models.PositiveIntegerField()),
                ("three_sharing_price", models.PositiveIntegerField()),
                ("four_sharing_price", models.PositiveIntegerField()),
                ("is_ac", models.BooleanField(default=False)),
                ("is_hot_water", models.BooleanField(default=False)),
                ("is_wifi", models.BooleanField(default=False)),
                ("is_washing_machine", models.BooleanField(default=False)),
                (
                    "room_cleaning_schedule",
                    models.CharField(default="Every day", max_length=100),
                ),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="registration_app.propertyinfo",
                    ),
                ),
            ],
        ),
    ]
